# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWh-A7kdFRzqvln4c7pDa69Wb58OjqZu
"""

# Import libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

# Get uploaded file name
filename = list(uploaded.keys())[0]

# Read image
image = cv2.imread(filename)

# Check if image is loaded
if image is None:
    print("Error: Unable to read the image.")
else:
    # Get image dimensions
    rows, cols = image.shape[:2]

    # Translation values
    tx = 100   # Move right by 100 pixels
    ty = 50    # Move down by 50 pixels

    # Translation matrix
    M = np.float32([[1, 0, tx],
                    [0, 1, ty]])

    # Apply translation
    translated = cv2.warpAffine(image, M, (cols, rows))

    # Convert BGR to RGB for display
    original_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    translated_rgb = cv2.cvtColor(translated, cv2.COLOR_BGR2RGB)

    # Display images
    plt.figure(figsize=(12,5))

    plt.subplot(1,2,1)
    plt.imshow(original_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(translated_rgb)
    plt.title("Translated Image")
    plt.axis("off")

    plt.show()

    # Save translated image
    cv2.imwrite("translated_image.jpg", translated)

    print("Image moved successfully!")
    print("Saved file: translated_image.jpg")