# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWh-A7kdFRzqvln4c7pDa69Wb58OjqZu
"""

# Import libraries
import cv2
import numpy as np
from google.colab import files

# Upload video
uploaded = files.upload()

# Get uploaded filename
filename = list(uploaded.keys())[0]

# Open video
cap = cv2.VideoCapture(filename)

# Get video properties
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

# Output video
out = cv2.VideoWriter('perspective_transformed_video.mp4',
                      cv2.VideoWriter_fourcc(*'mp4v'),
                      fps,
                      (width, height))

# Define source points
pts1 = np.float32([
    [50, 50],
    [width-50, 50],
    [50, height-50],
    [width-50, height-50]
])

# Define destination points
pts2 = np.float32([
    [0, 0],
    [width-1, 0],
    [100, height-1],
    [width-100, height-1]
])

# Compute Perspective Transformation Matrix
M = cv2.getPerspectiveTransform(pts1, pts2)

# Process video
while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Apply Perspective Transformation
    transformed = cv2.warpPerspective(frame, M, (width, height))

    # Write frame to output video
    out.write(transformed)

# Release resources
cap.release()
out.release()

print("Perspective Transformation completed successfully!")
print("Saved file: perspective_transformed_video.mp4")

# Download the output video
files.download("perspective_transformed_video.mp4")