# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

# Step 1: Import required libraries
from google.colab import files
import cv2
import matplotlib.pyplot as plt

# Step 2: Upload the image
uploaded = files.upload()

# Step 3: Get the uploaded file name
filename = list(uploaded.keys())[0]

# Step 4: Read the image
image = cv2.imread(filename)

# Check if the image is loaded successfully
if image is None:
    print("Error: Unable to load the image.")
else:
    # Convert BGR to RGB for displaying
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Convert the image to Grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Step 5: Apply Canny Edge Detection
    edges = cv2.Canny(gray, 100, 200)

    # Step 6: Display Original and Edge Images
    plt.figure(figsize=(12,6))

    plt.subplot(1,2,1)
    plt.imshow(image_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(edges, cmap='gray')
    plt.title("Canny Edge Detection")
    plt.axis("off")

    plt.show()