# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWh-A7kdFRzqvln4c7pDa69Wb58OjqZu
"""

# Import libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

# Get uploaded filename
filename = list(uploaded.keys())[0]

# Read image
image = cv2.imread(filename)

# Check if image is loaded
if image is None:
    print("Error: Unable to read the image.")
else:
    # Get image dimensions
    h, w = image.shape[:2]

    # Source points (Original Image)
    src_pts = np.float32([
        [50, 50],
        [w - 50, 50],
        [w - 50, h - 50],
        [50, h - 50]
    ])

    # Destination points (Warped Image)
    dst_pts = np.float32([
        [0, 100],
        [w - 100, 0],
        [w - 50, h - 100],
        [100, h - 50]
    ])

    # Compute Homography Matrix
    H, status = cv2.findHomography(src_pts, dst_pts)

    # Apply Homography Transformation
    transformed = cv2.warpPerspective(image, H, (w, h))

    # Convert BGR to RGB for display
    original_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    transformed_rgb = cv2.cvtColor(transformed, cv2.COLOR_BGR2RGB)

    # Display Images
    plt.figure(figsize=(12,5))

    plt.subplot(1,2,1)
    plt.imshow(original_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(transformed_rgb)
    plt.title("Homography Transformed Image")
    plt.axis("off")

    plt.show()

    # Save output image
    cv2.imwrite("homography_transformed.jpg", transformed)

    print("Homography Transformation completed successfully!")
    print("Saved file: homography_transformed.jpg")