# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWh-A7kdFRzqvln4c7pDa69Wb58OjqZu
"""

# Import libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

# Get uploaded filename
filename = list(uploaded.keys())[0]

# Read image
image = cv2.imread(filename)

# Check if image is loaded
if image is None:
    print("Error: Unable to read the image.")
else:
    h, w = image.shape[:2]

    # Source points
    src = np.array([
        [50, 50],
        [w-50, 50],
        [w-50, h-50],
        [50, h-50]
    ], dtype=np.float32)

    # Destination points
    dst = np.array([
        [0, 100],
        [w-100, 0],
        [w-50, h-100],
        [100, h-50]
    ], dtype=np.float32)

    # -------- Direct Linear Transformation (DLT) --------
    A = []

    for i in range(4):
        x, y = src[i]
        u, v = dst[i]

        A.append([-x, -y, -1, 0, 0, 0, u*x, u*y, u])
        A.append([0, 0, 0, -x, -y, -1, v*x, v*y, v])

    A = np.array(A)

    # Solve Ah = 0 using Singular Value Decomposition (SVD)
    U, S, Vt = np.linalg.svd(A)
    H = Vt[-1].reshape(3,3)

    # Normalize Homography Matrix
    H = H / H[2,2]

    # Apply Transformation
    transformed = cv2.warpPerspective(image, H, (w, h))

    # Convert BGR to RGB
    original_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    transformed_rgb = cv2.cvtColor(transformed, cv2.COLOR_BGR2RGB)

    # Display Images
    plt.figure(figsize=(12,5))

    plt.subplot(1,2,1)
    plt.imshow(original_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(transformed_rgb)
    plt.title("DLT Transformed Image")
    plt.axis("off")

    plt.show()

    # Save output
    cv2.imwrite("DLT_transformed.jpg", transformed)

    print("Direct Linear Transformation completed successfully!")
    print("Saved file: DLT_transformed.jpg")