# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhWVuGc1nx6B43-6xWwIQhfR1VF8bQ5-
"""

# Step 1: Import required libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Step 2: Upload an image
uploaded = files.upload()

# Step 3: Read the uploaded image
filename = list(uploaded.keys())[0]
image = cv2.imread(filename)

# Step 4: Convert image from BGR to RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Step 5: Create a blurred version of the image
blurred = cv2.GaussianBlur(image, (5, 5), 0)

# Step 6: Perform Unsharp Masking
# Original image + detail mask
sharpened = cv2.addWeighted(image, 1.5, blurred, -0.5, 0)

# Step 7: Convert sharpened image to RGB
sharpened_rgb = cv2.cvtColor(sharpened, cv2.COLOR_BGR2RGB)

# Step 8: Display original, blurred and sharpened images
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(cv2.cvtColor(blurred, cv2.COLOR_BGR2RGB))
plt.title("Blurred Image")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(sharpened_rgb)
plt.title("Unsharp Masking")
plt.axis("off")

plt.show()