# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

# Step 1: Import required libraries
from google.colab import files
import cv2
import matplotlib.pyplot as plt

# Step 2: Upload the image
uploaded = files.upload()

# Step 3: Get the uploaded filename
filename = list(uploaded.keys())[0]

# Step 4: Read the image
image = cv2.imread(filename)

# Check if image is loaded
if image is None:
    print("Error: Unable to load image.")
else:
    # Convert BGR to RGB for display
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Step 5: Scale the image

    # Smaller image (50% of original size)
    small_image = cv2.resize(image_rgb, None, fx=0.5, fy=0.5,
                             interpolation=cv2.INTER_AREA)

    # Bigger image (200% of original size)
    big_image = cv2.resize(image_rgb, None, fx=2.0, fy=2.0,
                           interpolation=cv2.INTER_LINEAR)

    # Step 6: Display the images
    plt.figure(figsize=(15,5))

    plt.subplot(1,3,1)
    plt.imshow(image_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(small_image)
    plt.title("Smaller Image (50%)")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(big_image)
    plt.title("Bigger Image (200%)")
    plt.axis("off")

    plt.show()