# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWh-A7kdFRzqvln4c7pDa69Wb58OjqZu
"""

# Import libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

# Get uploaded file name
filename = list(uploaded.keys())[0]

# Read image
image = cv2.imread(filename)

# Check if image is loaded
if image is None:
    print("Error: Unable to read the image.")
else:
    # Get image dimensions
    rows, cols = image.shape[:2]

    # Define three points from the original image
    pts1 = np.float32([[50, 50],
                       [200, 50],
                       [50, 200]])

    # Define corresponding points in the transformed image
    pts2 = np.float32([[10, 100],
                       [200, 50],
                       [100, 250]])

    # Compute Affine Transformation Matrix
    M = cv2.getAffineTransform(pts1, pts2)

    # Apply Affine Transformation
    transformed = cv2.warpAffine(image, M, (cols, rows))

    # Convert BGR to RGB for display
    original_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    transformed_rgb = cv2.cvtColor(transformed, cv2.COLOR_BGR2RGB)

    # Display images
    plt.figure(figsize=(12,5))

    plt.subplot(1,2,1)
    plt.imshow(original_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(transformed_rgb)
    plt.title("Affine Transformed Image")
    plt.axis("off")

    plt.show()

    # Save transformed image
    cv2.imwrite("affine_transformed.jpg", transformed)

    print("Affine Transformation completed successfully!")
    print("Saved file: affine_transformed.jpg")