# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

# Step 1: Import required libraries
from google.colab import files
import cv2
import matplotlib.pyplot as plt

# Step 2: Upload the image
uploaded = files.upload()

# Step 3: Get the uploaded file name
filename = list(uploaded.keys())[0]

# Step 4: Read the image
image = cv2.imread(filename)

# Check if the image is loaded successfully
if image is None:
    print("Error: Unable to load the image.")
else:
    # Convert BGR to RGB for displaying with Matplotlib
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Step 5: Apply Gaussian Blur
    # (Kernel size: 15x15, SigmaX = 0)
    blurred_image = cv2.GaussianBlur(image_rgb, (15, 15), 0)

    # Step 6: Display the Original and Blurred Images
    plt.figure(figsize=(12,6))

    plt.subplot(1,2,1)
    plt.imshow(image_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(blurred_image)
    plt.title("Gaussian Blurred Image")
    plt.axis("off")

    plt.show()