# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhWVuGc1nx6B43-6xWwIQhfR1VF8bQ5-
"""

# Step 1: Import required libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Step 2: Upload an image
uploaded = files.upload()

# Step 3: Read the uploaded image
filename = list(uploaded.keys())[0]
image = cv2.imread(filename)

# Step 4: Convert image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Step 5: Calculate gradients in X and Y directions
gradient_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
gradient_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)

# Step 6: Calculate gradient magnitude
gradient = cv2.magnitude(gradient_x, gradient_y)

# Step 7: Convert gradient to 8-bit
gradient = cv2.convertScaleAbs(gradient)

# Step 8: Create gradient mask
gradient_mask = gradient.astype(np.float32) / 255.0

# Step 9: Sharpen the original image using the gradient mask
image_float = image.astype(np.float32)

# Apply the mask to all color channels
gradient_mask_3ch = cv2.merge([
    gradient_mask, gradient_mask, gradient_mask
])

sharpened = image_float + (image_float * gradient_mask_3ch)

# Step 10: Keep pixel values between 0 and 255
sharpened = np.clip(sharpened, 0, 255).astype(np.uint8)

# Step 11: Convert images from BGR to RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
sharpened_rgb = cv2.cvtColor(sharpened, cv2.COLOR_BGR2RGB)

# Step 12: Display results
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(gradient, cmap="gray")
plt.title("Gradient Mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(sharpened_rgb)
plt.title("Gradient Mask Sharpened Image")
plt.axis("off")

plt.show()