# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhWVuGc1nx6B43-6xWwIQhfR1VF8bQ5-
"""

# Step 1: Import required libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Step 2: Upload an image
uploaded = files.upload()

# Step 3: Read the uploaded image
filename = list(uploaded.keys())[0]
image = cv2.imread(filename)

# Step 4: Define Laplacian mask with diagonal neighbors
laplacian_mask = np.array([
    [-1, -1, -1],
    [-1,  9, -1],
    [-1, -1, -1]
], dtype=np.float32)

# Step 5: Apply the Laplacian sharpening mask
sharpened = cv2.filter2D(image, -1, laplacian_mask)

# Step 6: Convert images from BGR to RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
sharpened_rgb = cv2.cvtColor(sharpened, cv2.COLOR_BGR2RGB)

# Step 7: Display original and sharpened images
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(sharpened_rgb)
plt.title("Sharpened Image - Laplacian with Diagonal Neighbors")
plt.axis("off")

plt.show()