# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhWVuGc1nx6B43-6xWwIQhfR1VF8bQ5-
"""

# Step 1: Import required libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Step 2: Upload an image
uploaded = files.upload()

# Step 3: Read the uploaded image
filename = list(uploaded.keys())[0]
image = cv2.imread(filename)

# Step 4: Convert image to RGB for display
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Step 5: Create a blurred image
blurred = cv2.GaussianBlur(image, (5, 5), 0)

# Step 6: Define the high-boost factor
A = 2.0

# Step 7: Perform High-Boost Filtering
# High-boost formula: g(x,y) = A*f(x,y) - blurred image
high_boost = cv2.addWeighted(image, A, blurred, -(A - 1), 0)

# Step 8: Convert result to RGB
high_boost_rgb = cv2.cvtColor(high_boost, cv2.COLOR_BGR2RGB)

# Step 9: Display original and sharpened images
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(high_boost_rgb)
plt.title("High-Boost Sharpened Image")
plt.axis("off")

plt.show()