# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhWVuGc1nx6B43-6xWwIQhfR1VF8bQ5-
"""

# Step 1: Import required libraries
import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Step 2: Upload an image
uploaded = files.upload()

# Step 3: Read the uploaded image
filename = list(uploaded.keys())[0]
image = cv2.imread(filename)

# Step 4: Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Step 5: Apply Canny Edge Detection
edges = cv2.Canny(gray, 100, 200)

# Step 6: Display original and edge-detected images
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(edges, cmap="gray")
plt.title("Canny Edge Detection")
plt.axis("off")

plt.show()