# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def record_video(filename='webcam.mp4'):
    js = Javascript('''
    async function recordVideo() {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Start Recording';
      div.appendChild(capture);

      const stop = document.createElement('button');
      stop.textContent = 'Stop Recording';
      div.appendChild(stop);

      document.body.appendChild(div);

      const stream = await navigator.mediaDevices.getUserMedia({video:true,audio:false});
      const video = document.createElement('video');
      video.style.display='block';
      document.body.appendChild(video);
      video.srcObject = stream;
      await video.play();

      const recorder = new MediaRecorder(stream);
      let chunks=[];

      recorder.ondataavailable=e=>chunks.push(e.data);

      capture.onclick=()=>recorder.start();

      const result = new Promise(resolve=>{
        stop.onclick=()=>{
          recorder.stop();
          recorder.onstop=()=>{
            const blob=new Blob(chunks,{type:'video/mp4'});
            const reader=new FileReader();
            reader.readAsDataURL(blob);
            reader.onloadend=()=>resolve(reader.result);
            stream.getTracks().forEach(track=>track.stop());
          }
        }
      });

      return await result;
    }
    ''')
    display(js)
    data = eval_js('recordVideo()')
    binary = b64decode(data.split(',')[1])

    with open(filename,'wb') as f:
        f.write(binary)

record_video()
print("Video Saved as webcam.mp4")

import cv2

cap = cv2.VideoCapture("webcam.mp4")

fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(3))
height = int(cap.get(4))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')

slow = cv2.VideoWriter("slow.mp4", fourcc, fps/2, (width,height))
fast = cv2.VideoWriter("fast.mp4", fourcc, fps*2, (width,height))

count=0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Slow Motion
    slow.write(frame)
    slow.write(frame)

    # Fast Motion
    if count%2==0:
        fast.write(frame)

    count+=1

cap.release()
slow.release()
fast.release()

print("Slow and Fast Motion Videos Created")

from IPython.display import Video

print("Original Video")
display(Video("webcam.mp4", embed=True))

print("Slow Motion Video")
display(Video("slow.mp4", embed=True))

print("Fast Motion Video")
display(Video("fast.mp4", embed=True))