# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

# Step 1: Import required libraries
from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 2: Upload the image
uploaded = files.upload()

# Step 3: Get the uploaded file name
filename = list(uploaded.keys())[0]

# Step 4: Read the image
image = cv2.imread(filename)

# Check if the image is loaded successfully
if image is None:
    print("Error: Unable to load the image.")
else:
    # Convert BGR to RGB for display
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Step 5: Create a kernel for dilation
    kernel = np.ones((5,5), np.uint8)

    # Step 6: Apply Dilation
    dilated_image = cv2.dilate(image_rgb, kernel, iterations=1)

    # Step 7: Display the Original and Dilated Images
    plt.figure(figsize=(12,6))

    plt.subplot(1,2,1)
    plt.imshow(image_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(dilated_image)
    plt.title("Dilated Image")
    plt.axis("off")

    plt.show()