# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWh-A7kdFRzqvln4c7pDa69Wb58OjqZu
"""

# Import libraries
import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

# Get uploaded file name
filename = list(uploaded.keys())[0]

# Read image
image = cv2.imread(filename)

# Check if image is loaded
if image is None:
    print("Error: Unable to read the image.")
else:
    # Rotate image
    clockwise = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)
    counter_clockwise = cv2.rotate(image, cv2.ROTATE_90_COUNTERCLOCKWISE)

    # Convert BGR to RGB for display
    original_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    clockwise_rgb = cv2.cvtColor(clockwise, cv2.COLOR_BGR2RGB)
    counter_rgb = cv2.cvtColor(counter_clockwise, cv2.COLOR_BGR2RGB)

    # Display images
    plt.figure(figsize=(15,5))

    plt.subplot(1,3,1)
    plt.imshow(original_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(clockwise_rgb)
    plt.title("90° Clockwise")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(counter_rgb)
    plt.title("90° Counter Clockwise")
    plt.axis("off")

    plt.show()

    # Save rotated images
    cv2.imwrite("clockwise.jpg", clockwise)
    cv2.imwrite("counter_clockwise.jpg", counter_clockwise)

    print("Rotation completed successfully!")
    print("Saved files: clockwise.jpg and counter_clockwise.jpg")