# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzsvgerUetZeEnfQG90U07_e-jecmAad
"""

# Step 1: Import required libraries
from google.colab import files
from IPython.display import HTML
from base64 import b64encode
import cv2

# Step 2: Upload the video
uploaded = files.upload()

# Step 3: Get uploaded filename
video_file = list(uploaded.keys())[0]

# Step 4: Read video
cap = cv2.VideoCapture(video_file)

# Get video properties
fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Create slow-motion video (half speed)
slow_out = cv2.VideoWriter(
    "slow_motion.mp4",
    cv2.VideoWriter_fourcc(*'mp4v'),
    fps/2,
    (width, height)
)

# Create fast-motion video (double speed)
fast_out = cv2.VideoWriter(
    "fast_motion.mp4",
    cv2.VideoWriter_fourcc(*'mp4v'),
    fps*2,
    (width, height)
)

# Process frames
while True:
    ret, frame = cap.read()

    if not ret:
        break

    # Slow motion (duplicate each frame)
    slow_out.write(frame)
    slow_out.write(frame)

    # Fast motion (write every alternate frame)
    fast_out.write(frame)
    cap.read()

cap.release()
slow_out.release()
fast_out.release()

print("Processing Completed!")

from IPython.display import Video

print("Original Video")
display(Video(video_file, embed=True))

print("Slow Motion")
display(Video("slow_motion.mp4", embed=True))

print("Fast Motion")
display(Video("fast_motion.mp4", embed=True))